### ISSUE TITLE
Update the definitions

### ISSUE THREAD

**Issue by giakki** [jdharmon/scryfallapi#1]
Hey there!
Thank you for your effort in compiling the swagger file for Scryfall, it has helped me a lot!

I noticed that their API has changed quite a bit, and I was wondering if I could submit a PR with the issues i have found:

- `card.layout` is missing the enum value `flip`  
- `card.all_parts` is now an array of `related_cards`  
- `card_face.color_indicator` is now an array of `colors`  
- `legal_status` is missing `banned` and `restricted`  

Cheers,
Giakki

**Comment by jdharmon** [comment]
Thanks for the finding the issues. They weren't posted to the API changelog. I'm happy to accept a PR if you want to fix them, or I'll make the changes when I have time.

**Comment by jdharmon** [comment]
Fixed in dedfc1e17ca359a17278ec15a0c9cc399861f31f.
